plugins {
    id 'com.gradleup.shadow'
    id 'net.raphimc.class-token-replacer'
}

sourceSets {
    main {
        classTokenReplacer {
            property("\${version}", project.version)
        }
    }
}

repositories {
    maven { url 'https://papermc.io/repo/repository/maven-public/' }
}

dependencies {
    implementation project(':dynamicpremium-commons')
    compileOnly 'com.velocitypowered:velocity-api:3.1.1'
    annotationProcessor 'com.velocitypowered:velocity-api:3.1.1'
}

jar {
    enabled = false
    dependsOn (shadowJar)
}

shadowJar {
    archiveClassifier.set('')
}